# -----------------------------
# Application Configuration
# -----------------------------
spring.application.name=Insurance-System

# -----------------------------
# Database Configuration
# -----------------------------
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/insurancesystem
spring.datasource.username=root
spring.datasource.password=Root

# -----------------------------
# JPA / Hibernate Configuration
# -----------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# -----------------------------
# Server Configuration
# -----------------------------
server.port=8181

# -----------------------------
# Email Configuration
# -----------------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yourmail@gmail.com
spring.mail.password=ypaf ctap dhha titn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true

# -----------------------------
# MSG91 Configuration (SMS)
# -----------------------------
msg91.authkey=475661ALmYcCrscDu369044eeaP1
msg91.sender=MSGIND
msg91.route=4
msg91.templateId=69045191150b2f2a03331754
msg91.apiUrl=https://control.msg91.com/api/v5/flow/

# -----------------------------
# JWT Configuration (Security)
# -----------------------------
app.jwt.secret=mySuperStrongSecretKeyForInsuranceSystem123456789
app.jwt.expiration-ms=900000
